// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqbtfyhpstzcxwuhtqsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxYnRmeWhwc3R6Y3h3dWh0cXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTg3NDcsImV4cCI6MjA1OTE5NDc0N30.y6cr8IoOz_yEYuLn65qONXidVM1fWAFzonFhSUAHiBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);